/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuLuca;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.util.Date;
/**
 *
 * @author klaydejr
 */
public class LucaPanel extends javax.swing.JPanel {

    private Font myFont;
    private Rectangle box;
    
    /**
     * Creates new form MyPanel_1
     */
    public LucaPanel() {
        initComponents();
        
        myFont = new Font("Serif", Font.BOLD, 20);
        box = new Rectangle(10,10,50,50);
        
    }
    
    public String getDate() {
        Date presDate = new Date();
        return presDate.toString();
    }
    
    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        
        g.setColor(new Color(255,200,200));
        g.fillRect(0, 0, 1000, 1000);
        g.setFont(myFont);
        
        g.setColor(Color.BLACK);
        g.drawString("LucaPanel", 50, 150);
        g.drawString(getDate(), 50, 175);
        
        g.setColor(Color.BLUE);
        g.fillRect(10,10,50,50);
    }
    
    public void moveRect(int oldX, int oldY, int newX, int newY) {
        
        this.getGraphics().clearRect(oldX, oldY, 50, 50);
        this.getGraphics().setColor(Color.BLUE);
        this.getGraphics().fillRect(newX, newY, 50, 50);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        System.out.println(evt.getX());
        if (
                (evt.getX() >= this.box.x && evt.getX() <= (this.box.x + this.box.width))  &&
                (evt.getY() >= this.box.y && evt.getY() <= (this.box.y + this.box.height)) 
            )
        {
            System.out.println("this is the box");
            moveRect(this.box.x, this.box.y, evt.getX()-25, evt.getY()-25);
            this.box.x = evt.getX() - 25;
            this.box.y = evt.getY() - 25;
            
        }
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if (
                (evt.getX() >= this.box.x && evt.getX() <= (this.box.x + this.box.width))  &&
                (evt.getY() >= this.box.y && evt.getY() <= (this.box.y + this.box.height)) 
            )
        {
            System.out.println("moving the box");
            moveRect(this.box.x, this.box.y, evt.getX()-25, evt.getY()-25);
            this.box.x = evt.getX() - 25;
            this.box.y = evt.getY() - 25;
        }
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
