
package demoMouse1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author klaydejr
 */
public class GamePanel extends javax.swing.JPanel implements MouseListener, MouseMotionListener{

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        
        addMouseListener(this);
        addMouseMotionListener(this);
        
    }
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        //System.out.println("paintComponent");
        g.setColor(Color.GREEN);
        g.fillRect(0,0,1000,1000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("mouseClicked at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mousePressed(MouseEvent e) {
        System.out.println("mousePressed at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        System.out.println("mouseReleased at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        System.out.println("mouseEntered at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mouseExited(MouseEvent e) {
        System.out.println("mouseExited at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        System.out.println("mouseDragged at "+e.getX()+", "+e.getY());
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        System.out.println("mouseMoved at "+e.getX()+", "+e.getY());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
