/*
 * Name: Andrew Moore
 * Date: 2/23/18
 * Class: MoorePanel
 * Description: Frame to hold the game Panel, Game/Project described in the 
 * MooreGamePanel decribition part of the comment header.
 * URL: https://drive.google.com/drive/folders/1iiLIuCfOQTNyZvxLSDEa0F-sjxPwsNvc
 * Enhancement(s): ***All done the MooreGamePanel***
 */

package stuMoore;

import java.awt.*;

/**
 * @author klaydejr
 * @author mooreaj2021
 */

public class MoorePanel extends javax.swing.JPanel{

    private Font myFont;
    private MooreGamePanel gamePanel;
    private MooreCat cat;
    public Boolean catClass=false;
    
    /**
     * Creates new form MyPanel_1
     */
    public MoorePanel() {
        initComponents();
        
        //<editor-fold defaultstate="collapsed" desc="Bound mouse reading bounds">
        gamePanel = new MooreGamePanel();
        gamePanel.setSize(700, 400);
        this.add(gamePanel);
        gamePanel.setLocation(35, 35);
        //</editor-fold>
        
        myFont = new Font("Serif", Font.BOLD, 22);
        
        cat = new MooreCat();
    }
    
    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        
        g.setColor(new Color(255,200,200));
        g.fillRect(0, 0, 1000, 1000);
        g.setFont(myFont);
        
        g.setColor(Color.BLACK);
        g.drawString("MoorePanel", 50, 25);
        g.drawString("Feb 23, 2018", 200, 25);
        
//        gamePanel.ActivateCatClass();
        if (catClass){
        System.out.println(cat.toString());
        g.drawString("MooreCat toString(): "+cat.toString(), 365, 25);
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
